settings:
  batch_size : 16
  num_workers : 0
  num_epochs : 50
  real_num_workers : 0 # real world data fine tuning epochs
  lr_rate : 1e-4
  mask_checkpoint : "src/model/weights_seg/Vortex0219_01.pth" # masking model
  checkpoint : "src/model/weights_reg/ViscSyn0325_01.pth" # freshly trained model 
  real_checkpoint : "src/model/weights_reg/ViscReal0321_01.pth" # freshly fine tuned model with real world data
  cnn : "resnet34"
  lstm_size : 256 # originally 128
  lstm_layers : 2
  real_num_epochs : 30
  frame_num : 10
  time : 10
  output_size : 3 # regression to density, dynamic viscosity, surface tension,
  eta_min : 1e-8

directories :
  data_root : "dataset/CFDfluid/" # use dataset/realfluid/videos to make masked real world dataset, and use videoToMask.mask_videos()
  video_subdir : "videos"
  para_subdir : "parametersNorm"
  save_root : "dataset/CFDfluid/processed_data"
  real_root : "dataset/realfluid/original"
  real_save_root : "dataset/realfluid/processed_data"