settings:
  batch_size : 96
  num_workers : 128
  num_epochs : 20
  lr_rate : 5e-4
  checkpoint : "preprocess/model_seg/Vortex0306_01.pth" # freshly trained model name
  base_checkpoint : "preprocess/model_seg/Vortex0219_01.pth" # pre-trained model name

directories:
  data_root : "dataset/WebGLfluid/original"
  image_subdir : "raw"
  mask_subdir : "masked"
  save_root : "dataset/WebGLfluid/processed_data"
  image_save_subdir : "images"
  mask_save_subdir : "masks"
  box_save_subdir : "boxes"