project: "real_world_calibration"
name: "test_run"
version: v0

regression:
  train_settings:
    batch_size : 2
    num_epochs : 30
    num_workers : 4
    seed : 1205
    dataset : "VideoDataset"

  preprocess:
    scaler : "logzscaler"    # log scaled, inter scaling works best 
    descaler : "logzdescaler"
    frame_num : 10
    time : 5
    test_size : 0.2
    random_state : 37
    rpm_class : 7
  
  model:
    encoder:
      encoder: "ResnetLSTM"
      cnn : "resnet34"
      cnn_train : True
      lstm_size : 256
      lstm_layers : 3
      output_size : 3 # 4 for rpm
      drop_rate : 0.3
      embedding_size : 512
      embed_weight : 0.5

    flow: 
      flow : "RealNVP"
      flow_bool : False
      dim: 4 # dimension of total model output, currently 4
      con_dim: 256 # same as lstm hidden_size
      hidden_dim: 64 # innate dimension of flow
      num_layers : 10 # number of s, t layers stacked

  real_model:
    real_epochs : 30
    lr : 1e-4
    weight_decay : 0

  loss : "MAPE"

  optimizer:
    optim_class: Adam
    scheduler_class: CosineAnnealingLR
    lr: 1e-5
    eta_min : 1e-10
    weight_decay: 5e-4
    patience : 10
  
  directories:
    checkpoint :
      ckpt_root : "src/weights/"
      # inf_checkpoint : "decay_5s_10fps_surfdensrpm_EMBED_test_run_0512_v6.pth"
      inf_checkpoint : "decay_5s_10fps_surfdensrpm_test_run_0424_v0.pth"

    data :
      data_root : "dataset/CFDArchive/decay_5s_10fps_surfdensrpm"
      test_root : "dataset/CFDArchive/test"
      real_root : "dataset/realfluid/RealArchive/decay_5s_10fps_hotplate"
      video_subdir : "videos"
      para_subdir : "parameters"
      norm_subdir : "parametersNorm"