project: "viscosity estimation testing"
name: "decay_5s_10fps_lowrpm_testrun"
version: v2

regression:
  train_settings:
    batch_size : 2
    num_epochs : 50
    num_workers : 4
    seed : 1205
    dataset : "VideoDataset"

  preprocess:
    scaler : "loginterscaler"    # log scaled, inter scaling works best 
    descaler : "loginterdescaler"
    frame_num : 10
    time : 5
    test_size : 0.2
    random_state : 37
  
  model:
    encoder:
      encoder: "ResnetLSTM"
      cnn : "resnet34"
      cnn_train : True
      lstm_size : 256
      lstm_layers : 3
      output_size : 3
      drop_rate : 0.3

    flow: 
      flow : "RealNVP"
      flow_bool : False
      dim: 4 # dimension of total model output, currently 4
      con_dim: 256 # same as lstm hidden_size
      hidden_dim: 64 # innate dimension of flow
      num_layers : 10 # number of s, t layers stacked

  real_model:
    real_num_epochs : 30

  loss : "MSLE" 
  # for normalized : MSLE, MAPE good for normalized values; 

  optimizer:
    optim_class: Adam
    scheduler_class: CosineAnnealingLR
    lr: 1e-5
    eta_min : 1e-10
    weight_decay: 5e-4
    patience : 15
  
  directories:
    checkpoint :
      mask_checkpoint : "src/weights/segmentation/Vortex0219_01.pth"
      checkpoint : "src/weights/"
      real_checkpoint : "src/models/weights_reg/ViscRealXXXX_01.pth"

    data :
      data_root : "dataset/decay_5s_10fps_lowrpm"
      video_subdir : "videos"
      para_subdir : "parameters"
      norm_subdir : "parametersNorm"
      save_root : "dataset/CFDfluid/processed_data" 
      real_root : "dataset/realfluid/original"
      real_save_root : "dataset/realfluid/processed_data"
      test_root : "dataset/CFDArchive/test"

segmentation:
  settings:
    batch_size : 96
    num_workers : 128
    num_epochs : 20
    lr_rate : 1e-4
    checkpoint : "preprocess/model_seg/Vortex0306_01.pth" # freshly trained model name
    base_checkpoint : "preprocess/model_seg/Vortex0219_01.pth" # pre-trained model name

  directories:
    data_root : "dataset/WebGLfluid/original"
    image_subdir : "raw"
    mask_subdir : "masked"
    save_root : "dataset/WebGLfluid/processed_data"
    image_save_subdir : "images"
    mask_save_subdir : "masks"
    box_save_subdir : "boxes"