project: "sph_test_run"
name: "classification_vivit_run"
version: v0

regression:
  train_settings:
    batch_size : 2
    num_epochs : 20
    num_workers : 0
    seed : 1205
    dataset : "VideoDatasetClass"

  preprocess:
    scaler : "interscaler"    # log scaled, inter scaling works best 
    descaler : "interdescaler"
    frame_num : 10
    time : 3.2
    test_size : 0.2
    random_state : 37
    rpm_class : 50
    aug_bool : False
  
  model:
    encoder:
      encoder: ResnetLSTMClass
      cnn : "resnet34"
      cnn_train : True
      lstm_size : 256
      lstm_layers : 5
      output_size : 3
      drop_rate : 0.2
      embedding_size : 512
      embed_weight : 0.0

    flow: 
      flow : "RealNVP"
      flow_bool : False
      dim: 4 # dimension of total model output, currently 4
      con_dim: 256 # same as lstm hidden_size
      hidden_dim: 64 # innate dimension of flow
      num_layers : 10 # number of s, t layers stacked

  real_model:
    real_epochs : 50
    lr : 1e-4
    weight_decay : 1e-5

  loss : "CE"

  optimizer:
    optim_class: Adam
    scheduler_class: CosineAnnealingLR
    lr: 1e-3
    eta_min : 1e-9
    weight_decay: 0
    patience : 10
  
  directories:
    checkpoint :
      ckpt_root : "src/weights/"
      inf_checkpoint : "src/weights/classification_lstm_run_0715_v0.pth"

    data :
      data_root : "dataset/CFDArchive/sph_improved"
      test_root : "dataset/CFDArchive/test"
      real_root : "dataset/realfluid/RealArchive/decay_5s_10fps_impeller"
      video_subdir : "videos"
      para_subdir : "parameters"
      norm_subdir : "parametersNorm"