project: "real_world_calibration"
name: "onlyVisc_rpmContEmbed"
version: v0

regression:
  train_settings:
    batch_size : 2
    num_epochs : 30
    num_workers : 0
    seed : 1205
    dataset : "VideoDatasetEmbed"

  preprocess:
    scaler : "logzscaler"    # log scaled, inter scaling works best 
    descaler : "logzdescaler"
    frame_num : 10
    time : 5
    test_size : 0.2
    random_state : 37
    rpm_class : 7
  
  model:
    encoder:
      encoder: "ResnetLSTMEmbedAdd"
      cnn : "resnet34"
      cnn_train : True
      lstm_size : 256
      lstm_layers : 3
      output_size : 3
      drop_rate : 0.2
      embedding_size : 512
      embed_weight : 2

    flow: 
      flow : "RealNVP"
      flow_bool : False
      dim: 4 # dimension of total model output, currently 4
      con_dim: 256 # same as lstm hidden_size
      hidden_dim: 64 # innate dimension of flow
      num_layers : 10 # number of s, t layers stacked

  real_model:
    real_epochs : 50
    lr : 1e-4
    weight_decay : 1e-5

  loss : "MAPErpm"

  optimizer:
    optim_class: Adam
    scheduler_class: CosineAnnealingLR
    lr: 1e-4
    eta_min : 1e-10
    weight_decay: 0
    patience : 5
  
  directories:
    checkpoint :
      ckpt_root : "src/weights/"
      inf_checkpoint : "src/weights/onlyVisc_rpmContEmbed_loss_weight_inc_0618_v0.pth"

    data :
      data_root : "dataset/CFDArchive/decay_5s_10fps_surfdensrpm"
      test_root : "dataset/CFDArchive/test"
      real_root : "dataset/realfluid/RealArchive/decay_5s_10fps_hotplate"
      video_subdir : "videos"
      para_subdir : "parameters"
      norm_subdir : "parametersNorm"